### PR TITLE
Full encoding support

### PR DESCRIPTION
**Pull request by devinstewart**

### CODE REVIEW

**Review by kanongil — CHANGES_REQUESTED** [review]
This contains two unrelated features and should be split into separate PRs to properly review each.

That being said, I would not bother with the non-utf8 encoded string support, as it adds extra complexity without any apparent gains, per https://github.com/hapijs/jwt/issues/21#issuecomment-751596786.

**Comment by kanongil** [comment]
FYI if you append "Closes #XX" to the relevant commit messages, it will link the commit to the issue, and automatically close it when merged.

**Comment by devinstewart** [comment]
Sure thing Gil.  I originally combined them thinking they would be touching the same lines of code, but now looking they are completely independent.

**Comment by devinstewart** [comment]
@hapijs/tsc - What say you?

I have removed the headless stuff and put it in its own PR.  On this guy I see two ways to go

1.  Merge this in
2. Close this guy and create a new PR that just changes:
```js
const value = `${Utils.b64stringify(header)}.${Utils.b64stringify(content, options.encoding || 'utf8')}`;
```
to:
```js
const value = `${Utils.b64stringify(header)}.${Utils.b64stringify(content)}`;
```
So that there is no confusion in the future.

I am good with either.

**Comment by devinstewart** [comment]
Rebased w/ the headless stuff in master.  LMK what you think on this guy.  As stated above, I'm cool with either keeping it or killing it.

If put to a vote I would lean towards keeping it, since [node-jws](https://github.com/auth0/node-jws#jwssignoptions) supports it on sign.  However I personally would never use it.

I believe this module was initially created due to an objection that the implementation of encode/decode by node-jws (or more specifically node-jwa) was _inefficient_.

I would not like to lose any features even if they are obscure.  Unless of course those features are also _inefficient_.

**Review by kanongil — COMMENTED** [review]
Supporting alternate encodings creates new code paths that could enable new attacks on the module security. As such, I would strongly advise not to complicate the implementation without good cause.

**Comment by devinstewart** [comment]
@kanongil - I'm convinced.  Will create new PR with a lot less code.

**Pull request closed without merging**
