### PR TITLE
fix: make compliant with jwt spec

### PR DESCRIPTION
**Pull request by skoshx**
This commit makes @hapi/jwt compliant with the JWT specificiation

### CODE REVIEW

**Comment by kanongil** [comment]
Seems legit according to: https://datatracker.ietf.org/doc/html/rfc7519#section-5.1

@skoshx You need to update the tests so the test suite passes.

**Comment by devinstewart** [comment]
This was put in due to https://github.com/hapijs/jwt/issues/27.

The last line of https://datatracker.ietf.org/doc/html/rfc7519#section-5.1 states: _Use of this Header Parameter is OPTIONAL._

**Comment by skoshx** [comment]
@devinstewart The spec states that the `typ` parameter can contain values other than "JWT", in our OAuth2 flow for example, it is "at+jwt", so the current implementation requiring it to be "JWT" is not compliant with the specification.

**Comment by kanongil** [comment]
> The last line of https://datatracker.ietf.org/doc/html/rfc7519#section-5.1 states: _Use of this Header Parameter is OPTIONAL._

It also states: *This parameter is **ignored by JWT implementations**; any processing of this parameter is performed by the JWT application*.

AFAIK, this is an implementation and should thus ignore the value when decoding.

**Comment by skoshx** [comment]
friendly bump, what is the status on this Pull Request? Tests are passing and this is a vital Pull Request since it fixes a breaking problem...

**Comment by devinstewart** [comment]
Agreed.  It originally required the `typ` to exist **and** be "JWT".

 In #27, `typ` was allowed to be optional, but if existed still needed to be "JWT".

This now completely adheres the the spec.

**Comment by devinstewart** [comment]
@skoshx, friendly bump to the @hapijs/tsc  to get land this bug fix.

Thanks for your contribution, sorry for the delay and confusion.

**Comment by devinivy** [comment]
Published as v2.1.1— thanks!

**Pull request merged**
